package Vistas;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import desplazable.Desface;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.EventQueue;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

public class dashboardpanel extends javax.swing.JPanel {

  
    public dashboardpanel() {
        
        // Configuramos FlatLaf como el LookAndFeel
        try {
            FlatLightLaf.setup(); // Usamos FlatLaf en su versión clara
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        // Inicializamos los componentes
        initComponents();        
        
        // Configuramos el color de fondo y el layout
        setBackground(new Color(0, 0, 0, 0)); // Fondo transparente

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPlegable = new Vistas.elemetos.RadialGradientPanelRedondeado();
        jButton1 = new javax.swing.JButton();
        radialGradientPanelRedondeado6 = new Vistas.elemetos.RadialGradientPanelRedondeado();
        whiteRoundedPanelF1 = new Vistas.elementosTwo.WhiteRoundedPanelF();
        transparenteRoundedPanel1 = new Vistas.elementosTwo.TransparenteRoundedPanel();
        lbl_inicio = new javax.swing.JLabel();
        lbl_carros = new javax.swing.JLabel();
        lbl_citas = new javax.swing.JLabel();
        lbl_facturas = new javax.swing.JLabel();
        lbl_proveedores = new javax.swing.JLabel();
        lbl_ventas = new javax.swing.JLabel();
        lbl_usuarios_y_empleados = new javax.swing.JLabel();
<<<<<<< HEAD
        lbl_citas = new javax.swing.JLabel();
        lbl_inicio = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelContent = new Vistas.elemetos.RadialGradientPanelRedondeado();
        radialGradientPanelRedondeado6 = new Vistas.elemetos.RadialGradientPanelRedondeado();
        img_perfil = new javax.swing.JLabel();
        lbl_perfil = new javax.swing.JLabel();
=======
        panelContent = new Vistas.elementosTwo.TransparenteRoundedPanel();
        transparenteRoundedPanel2 = new Vistas.elementosTwo.TransparenteRoundedPanel();
        imgMinimize = new javax.swing.JLabel();
        imgExit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
>>>>>>> 6cd143adcee280f9bb955a55c2e36367ac1e3ff4
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        menuPlegable.setBackground(new java.awt.Color(8, 23, 46));

        jButton1.setText("Change calendar mode");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPlegableLayout = new javax.swing.GroupLayout(menuPlegable);
        menuPlegable.setLayout(menuPlegableLayout);
        menuPlegableLayout.setHorizontalGroup(
            menuPlegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPlegableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );
        menuPlegableLayout.setVerticalGroup(
            menuPlegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPlegableLayout.createSequentialGroup()
                .addGap(597, 597, 597)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        radialGradientPanelRedondeado6.setBackground(new java.awt.Color(8, 23, 46));

<<<<<<< HEAD
        img_perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/ic_perfil.png"))); // NOI18N

        lbl_perfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_perfil.setForeground(new java.awt.Color(255, 255, 255));
        lbl_perfil.setText("Sesión iniciada como:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("Admin");

=======
>>>>>>> 6cd143adcee280f9bb955a55c2e36367ac1e3ff4
        javax.swing.GroupLayout radialGradientPanelRedondeado6Layout = new javax.swing.GroupLayout(radialGradientPanelRedondeado6);
        radialGradientPanelRedondeado6.setLayout(radialGradientPanelRedondeado6Layout);
        radialGradientPanelRedondeado6Layout.setHorizontalGroup(
            radialGradientPanelRedondeado6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
            .addGroup(radialGradientPanelRedondeado6Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(radialGradientPanelRedondeado6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(img_perfil)
                .addContainerGap(754, Short.MAX_VALUE))
        );
        radialGradientPanelRedondeado6Layout.setVerticalGroup(
            radialGradientPanelRedondeado6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radialGradientPanelRedondeado6Layout.createSequentialGroup()
                .addGroup(radialGradientPanelRedondeado6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(radialGradientPanelRedondeado6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_perfil)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, radialGradientPanelRedondeado6Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(img_perfil)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
=======
            .addGap(0, 1063, Short.MAX_VALUE)
        );
        radialGradientPanelRedondeado6Layout.setVerticalGroup(
            radialGradientPanelRedondeado6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
>>>>>>> 6cd143adcee280f9bb955a55c2e36367ac1e3ff4
        );

        setBackground(new java.awt.Color(0, 0, 0));

        whiteRoundedPanelF1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_inicio.setBackground(new java.awt.Color(255, 255, 255));
        lbl_inicio.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_inicio.setForeground(new java.awt.Color(0, 27, 59));
        lbl_inicio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/ichomew.png"))); // NOI18N
        lbl_inicio.setText("Inicio");
        lbl_inicio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        lbl_inicio.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbl_inicio.setIconTextGap(40);
        lbl_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_inicioMouseClicked(evt);
            }
        });

        lbl_carros.setBackground(new java.awt.Color(0, 0, 0));
        lbl_carros.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_carros.setForeground(new java.awt.Color(0, 27, 59));
        lbl_carros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_carros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/iccarw.png"))); // NOI18N
        lbl_carros.setText("Carros");
        lbl_carros.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        lbl_carros.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbl_carros.setIconTextGap(40);
        lbl_carros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_carrosMouseClicked(evt);
            }
        });

        lbl_citas.setBackground(new java.awt.Color(255, 255, 255));
        lbl_citas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_citas.setForeground(new java.awt.Color(0, 27, 59));
        lbl_citas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_citas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/iccitasw.png"))); // NOI18N
        lbl_citas.setText("Citas");
        lbl_citas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        lbl_citas.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbl_citas.setIconTextGap(40);
        lbl_citas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_citasMouseClicked(evt);
            }
        });

        lbl_facturas.setBackground(new java.awt.Color(255, 255, 255));
        lbl_facturas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_facturas.setForeground(new java.awt.Color(0, 27, 59));
        lbl_facturas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_facturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/icfacturacionw.png"))); // NOI18N
        lbl_facturas.setText("Facturación");
        lbl_facturas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        lbl_facturas.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbl_facturas.setIconTextGap(40);
        lbl_facturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_facturasMouseClicked(evt);
            }
        });

        lbl_proveedores.setBackground(new java.awt.Color(255, 255, 255));
        lbl_proveedores.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_proveedores.setForeground(new java.awt.Color(0, 27, 59));
        lbl_proveedores.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/icproveedoresw.png"))); // NOI18N
        lbl_proveedores.setText("Proveedores");
        lbl_proveedores.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        lbl_proveedores.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbl_proveedores.setIconTextGap(40);
        lbl_proveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_proveedoresMouseClicked(evt);
            }
        });

        lbl_ventas.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ventas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_ventas.setForeground(new java.awt.Color(0, 27, 59));
        lbl_ventas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/icstadisticsw.png"))); // NOI18N
        lbl_ventas.setText("Ventas");
        lbl_ventas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        lbl_ventas.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbl_ventas.setIconTextGap(40);
        lbl_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ventasMouseClicked(evt);
            }
        });

        lbl_usuarios_y_empleados.setBackground(new java.awt.Color(255, 255, 255));
        lbl_usuarios_y_empleados.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_usuarios_y_empleados.setForeground(new java.awt.Color(0, 27, 59));
        lbl_usuarios_y_empleados.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_usuarios_y_empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/icusersw.png"))); // NOI18N
        lbl_usuarios_y_empleados.setText("Usuarios");
        lbl_usuarios_y_empleados.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        lbl_usuarios_y_empleados.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbl_usuarios_y_empleados.setIconTextGap(40);
        lbl_usuarios_y_empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_usuarios_y_empleadosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout transparenteRoundedPanel1Layout = new javax.swing.GroupLayout(transparenteRoundedPanel1);
        transparenteRoundedPanel1.setLayout(transparenteRoundedPanel1Layout);
        transparenteRoundedPanel1Layout.setHorizontalGroup(
            transparenteRoundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparenteRoundedPanel1Layout.createSequentialGroup()
                .addGroup(transparenteRoundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbl_carros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_inicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_citas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_facturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_proveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_usuarios_y_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        transparenteRoundedPanel1Layout.setVerticalGroup(
            transparenteRoundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparenteRoundedPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lbl_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_carros, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_citas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_facturas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_usuarios_y_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        whiteRoundedPanelF1.add(transparenteRoundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 290, 680));

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        whiteRoundedPanelF1.add(panelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 1040, 670));

        imgMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/icminimizew.png"))); // NOI18N
        imgMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgMinimizeMouseClicked(evt);
            }
        });

        imgExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/icexitw.png"))); // NOI18N
        imgExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgExitMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/icperfilw.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 27, 59));
        jLabel6.setText("Admin");

        javax.swing.GroupLayout transparenteRoundedPanel2Layout = new javax.swing.GroupLayout(transparenteRoundedPanel2);
        transparenteRoundedPanel2.setLayout(transparenteRoundedPanel2Layout);
        transparenteRoundedPanel2Layout.setHorizontalGroup(
            transparenteRoundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transparenteRoundedPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 756, Short.MAX_VALUE)
                .addComponent(imgMinimize)
                .addGap(2, 2, 2)
                .addComponent(imgExit)
                .addGap(15, 15, 15))
        );
        transparenteRoundedPanel2Layout.setVerticalGroup(
            transparenteRoundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparenteRoundedPanel2Layout.createSequentialGroup()
                .addGroup(transparenteRoundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transparenteRoundedPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(transparenteRoundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(imgMinimize)
                            .addComponent(imgExit)))
                    .addGroup(transparenteRoundedPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel6)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        whiteRoundedPanelF1.add(transparenteRoundedPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 1040, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/dashboardfondoblanco.png"))); // NOI18N
        whiteRoundedPanelF1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(whiteRoundedPanelF1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(whiteRoundedPanelF1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
    
    private void lbl_menuPlegableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_menuPlegableMouseClicked
      
         if (menuPlegable.getX() == 0) {
            desplace.desplazarIzquierda(menuPlegable, menuPlegable.getX(), -170, 10, 10);
        } else if (menuPlegable.getX() == -170) {
            desplace.desplazarDerecha(menuPlegable, menuPlegable.getX(), 0, 10, 10);
        }
    }//GEN-LAST:event_lbl_menuPlegableMouseClicked

=======
>>>>>>> 6cd143adcee280f9bb955a55c2e36367ac1e3ff4
    private void lbl_proveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_proveedoresMouseClicked
        frmProveedor pr = new frmProveedor();
    pr.setSize(1040, 670);
    pr.setLocation(0, 0);
    
    panelContent.removeAll();
    panelContent.add(pr, BorderLayout.CENTER);
    panelContent.revalidate();
    panelContent.repaint();
    }//GEN-LAST:event_lbl_proveedoresMouseClicked

    private void lbl_inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_inicioMouseClicked
        frmInicio in = new frmInicio();
    in.setSize(1040, 670);
    in.setLocation(0, 0);
    setBackground(new Color(0, 0, 0, 0)); // Fondo transparente
    panelContent.removeAll();
    panelContent.add(in, BorderLayout.CENTER);
    panelContent.revalidate();
    panelContent.repaint();
    
    }//GEN-LAST:event_lbl_inicioMouseClicked

    private void lbl_carrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_carrosMouseClicked
        frmClientes cr = new frmClientes();
    cr.setSize(1040, 670);
    cr.setLocation(0, 0);
     setBackground(new Color(0, 0, 0, 0)); // Fondo transparente
    panelContent.removeAll();
    panelContent.add(cr, BorderLayout.CENTER);
    panelContent.revalidate();
    panelContent.repaint();
    }//GEN-LAST:event_lbl_carrosMouseClicked

    private void lbl_citasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_citasMouseClicked
        frmCitas ct = new frmCitas();
    ct.setSize(1040, 670);
    ct.setLocation(0, 0);
     setBackground(new Color(0, 0, 0, 0)); // Fondo transparente
    panelContent.removeAll();
    panelContent.add(ct, BorderLayout.CENTER);
    panelContent.revalidate();
    panelContent.repaint();
    }//GEN-LAST:event_lbl_citasMouseClicked

    private void lbl_facturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_facturasMouseClicked
    frmFacturacion fr = new frmFacturacion();
    fr.setSize(1040, 670);
    fr.setLocation(0, 0);
     setBackground(new Color(0, 0, 0, 0)); // Fondo transparente
    panelContent.removeAll();
    panelContent.add(fr, BorderLayout.CENTER);
    panelContent.revalidate();
    panelContent.repaint();
    }//GEN-LAST:event_lbl_facturasMouseClicked

    private void lbl_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ventasMouseClicked
        frmVentas vt = new frmVentas();
    vt.setSize(1040, 670);
    vt.setLocation(0, 0);
     setBackground(new Color(0, 0, 0, 0)); // Fondo transparente
    panelContent.removeAll();
    panelContent.add(vt, BorderLayout.CENTER);
    panelContent.revalidate();
    panelContent.repaint();
    }//GEN-LAST:event_lbl_ventasMouseClicked

    private void lbl_perfilMouseClicked(java.awt.event.MouseEvent evt) {   
        frmPerfilAd fp = new frmPerfilAd();  
    fp.setSize(922, 703);
    fp.setLocation(0, 0);

    panelContent.removeAll(); // Limpiar el contenido anterior
    panelContent.add(fp, BorderLayout.CENTER); // Agregar el nuevo panel
    panelContent.revalidate(); // Validar el nuevo contenido
    panelContent.repaint(); // Actualizar la vista
}

    
    private void lbl_usuarios_y_empleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_usuarios_y_empleadosMouseClicked
        frmUsuarios us = new frmUsuarios();
    us.setSize(1040, 670);
    us.setLocation(0, 0);
     setBackground(new Color(0, 0, 0, 0)); // Fondo transparente
    panelContent.removeAll();
    panelContent.add(us, BorderLayout.CENTER);
    panelContent.revalidate();
    panelContent.repaint();
    }//GEN-LAST:event_lbl_usuarios_y_empleadosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!FlatLaf.isLafDark()) {
            EventQueue.invokeLater(() -> {
                FlatAnimatedLafChange.showSnapshot();
                FlatDarculaLaf.setup();
                FlatLaf.updateUI();
                FlatAnimatedLafChange.hideSnapshotWithAnimation();
            });
        } else {
            EventQueue.invokeLater(() -> {
                FlatAnimatedLafChange.showSnapshot();
                FlatIntelliJLaf.setup();
                FlatLaf.updateUI();
                FlatAnimatedLafChange.hideSnapshotWithAnimation();
            });
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void imgMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgMinimizeMouseClicked
           JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);  // Obtiene el JFrame que contiene el JPanel
    if (frame != null) {
        frame.setState(JFrame.ICONIFIED);  // Minimiza el JFrame
    }
    }//GEN-LAST:event_imgMinimizeMouseClicked

    private void imgExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgExitMouseClicked
        System.exit(0);  // Cierra la aplicación por completo
    }//GEN-LAST:event_imgExitMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    public javax.swing.JLabel img_perfil;
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
=======
    public javax.swing.JLabel imgExit;
    public javax.swing.JLabel imgMinimize;
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
>>>>>>> 6cd143adcee280f9bb955a55c2e36367ac1e3ff4
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_carros;
    private javax.swing.JLabel lbl_citas;
    private javax.swing.JLabel lbl_facturas;
    private javax.swing.JLabel lbl_inicio;
<<<<<<< HEAD
    private javax.swing.JLabel lbl_menuPlegable;
    private javax.swing.JLabel lbl_perfil;
=======
>>>>>>> 6cd143adcee280f9bb955a55c2e36367ac1e3ff4
    private javax.swing.JLabel lbl_proveedores;
    private javax.swing.JLabel lbl_usuarios_y_empleados;
    private javax.swing.JLabel lbl_ventas;
    private Vistas.elemetos.RadialGradientPanelRedondeado menuPlegable;
    public Vistas.elementosTwo.TransparenteRoundedPanel panelContent;
    private Vistas.elemetos.RadialGradientPanelRedondeado radialGradientPanelRedondeado6;
    private Vistas.elementosTwo.TransparenteRoundedPanel transparenteRoundedPanel1;
    private Vistas.elementosTwo.TransparenteRoundedPanel transparenteRoundedPanel2;
    private Vistas.elementosTwo.WhiteRoundedPanelF whiteRoundedPanelF1;
    // End of variables declaration//GEN-END:variables
}
