/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Controlador.ctrlAsignarOrden;
import Modelo.mdlAsignarOrden;
import Modelo.Servicios;
import Modelo.EstadoAsignarOrden;
import Modelo.mdlCitas;
import Vistas.elementosTwo.TransparenteRoundedPanel;
import com.toedter.calendar.JCalendar;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;


/**
 *
 * @author jjove
 */
public class frmAsignarOrden extends TransparenteRoundedPanel {

    /**
     * Creates new form frmAsignarOrden
     */
    public frmAsignarOrden() {
        initComponents();
        
        frmAsignarOrden vista = this;
        mdlAsignarOrden modelito = new mdlAsignarOrden();
        mdlCitas modelito1 = new mdlCitas();
        Servicios Modelo = new Servicios();
        EstadoAsignarOrden Modelo1 = new EstadoAsignarOrden();         
        ctrlAsignarOrden contro = new ctrlAsignarOrden(modelito, vista,modelito1,Modelo, Modelo1);
        vista.setVisible(true);
        
        txtFechaAsignacion.setEditable(false);
        txtFechaFinalizacion.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbCita = new javax.swing.JComboBox<>();
        cmbServicio = new javax.swing.JComboBox<>();
        cmbEstado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtFechaAsignacion = new javax.swing.JTextField();
        txtFechaFinalizacion = new javax.swing.JTextField();
        CalendarioFechaAsignacion = new com.toedter.calendar.JCalendar();
        jLabel8 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAsignaciones = new javax.swing.JTable();
        btnAgregar = new Vistas.elemetos.ButtonWI();
        btnLimpiar = new Vistas.elemetos.ButtonWI();
        btnActualizar = new Vistas.elemetos.ButtonWI();
        btnEliminar = new Vistas.elemetos.ButtonWI();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/crearuser.png"))); // NOI18N
        jLabel1.setText("Crear una asignacion de tarea para un empleado");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cita seleccionada para hacer el servicio:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Servicio a realizar:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Estado del trabajo a realizar:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Carro del cliente:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Límite de entrega:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Descripción:");
        jLabel7.setToolTipText("");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        cmbCita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 210, 30));

        cmbServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 210, 30));

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 210, 30));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 330, 60));
        add(txtFechaAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 210, 30));
        add(txtFechaFinalizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 330, 30));

        CalendarioFechaAsignacion.setBackground(new java.awt.Color(255, 255, 255));
        CalendarioFechaAsignacion.setForeground(new java.awt.Color(255, 255, 255));
        CalendarioFechaAsignacion.setSundayForeground(new java.awt.Color(0, 0, 0));
        CalendarioFechaAsignacion.setWeekdayForeground(new java.awt.Color(0, 0, 0));
        CalendarioFechaAsignacion.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CalendarioFechaAsignacionPropertyChange(evt);
            }
        });
        add(CalendarioFechaAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 329, 180));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha a seleccionar (hoy) :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        txtCliente.setActionCommand("<Not Set>");
        add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 210, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha de trabajo asignado:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        tbAsignaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbAsignaciones);

        btnAgregar.setText("Guardar");
        btnAgregar.setSuffixIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/icguardaraloadriel.png"))); // NOI18N

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setSuffixIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/iclimpiaralojaime.png"))); // NOI18N

        btnActualizar.setText("Editar");
        btnActualizar.setSuffixIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/iceditaralokevon.png"))); // NOI18N

        btnEliminar.setText("Eliminar");
        btnEliminar.setSuffixIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/icborraralojosue.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 980, 250));
    }// </editor-fold>//GEN-END:initComponents

    private void CalendarioFechaAsignacionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CalendarioFechaAsignacionPropertyChange
 if ("calendar".equals(evt.getPropertyName())) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        // Obtener la fecha seleccionada en el calendario de asignación
        Date fechaSeleccionada = CalendarioFechaAsignacion.getDate();

        // Actualizar el campo de texto de la fecha de asignación
        txtFechaAsignacion.setText(dateFormat.format(fechaSeleccionada));

        // Calcular la fecha de finalización (20 días después)
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(fechaSeleccionada);
        calendar.add(Calendar.DAY_OF_YEAR, 7);
        Date fechaFinalizacion = calendar.getTime();

        // Actualizar el campo de texto de la fecha de finalización
        txtFechaFinalizacion.setText(dateFormat.format(fechaFinalizacion));
    }
    }//GEN-LAST:event_CalendarioFechaAsignacionPropertyChange

    
     private void initCalendarios() {
     Calendar today = Calendar.getInstance();
    Date currentDate = today.getTime();

    // Establecer la fecha mínima y máxima seleccionable
    CalendarioFechaAsignacion.setMinSelectableDate(currentDate); // Mínimo hoy

    today.add(Calendar.DAY_OF_YEAR, 1); // Máximo mañana
    Date tomorrowDate = today.getTime();
    CalendarioFechaAsignacion.setMaxSelectableDate(tomorrowDate); // Máximo mañana

    // Inicializar el campo de texto con la fecha de asignación actual
    txtFechaAsignacion.setText(new SimpleDateFormat("yyyy-MM-dd").format(currentDate));

    // Calcular y establecer la fecha de finalización (7 días después de hoy)
    today.add(Calendar.DAY_OF_YEAR, 7); // Ya se añadió un día antes, por eso 19 más
    Date fechaFinalizacion = today.getTime();
    txtFechaFinalizacion.setText(new SimpleDateFormat("yyyy-MM-dd").format(fechaFinalizacion));

    // Aplicar restricciones adicionales si es necesario
    restrictCalendar(CalendarioFechaAsignacion);
}
    
    private Date fechaSeleccionada = null; // Variable para almacenar la fecha seleccionada
    
    private void restrictCalendar(JCalendar calendar) {
      // Listener para el cambio de fecha en el calendario
    disableMonthYearSelectors(calendar);

    // Listener para el cambio de fecha
    calendar.addPropertyChangeListener("calendar", evt -> {
        Date fechaSeleccionada = calendar.getDate();
        updateTextFields(fechaSeleccionada); // Actualizar los text fields

        if (calendar == CalendarioFechaAsignacion) {
            // Calcular la fecha de finalización 7 días después
            Calendar cal = Calendar.getInstance();
            cal.setTime(fechaSeleccionada);
            cal.add(Calendar.DAY_OF_YEAR, 7);
            Date fechaFinalizacion = cal.getTime();
            txtFechaFinalizacion.setText(new SimpleDateFormat("yyyy-MM-dd").format(fechaFinalizacion));
        }
    });
}
    
    private void disableMonthYearSelectors(JCalendar calendar) {
    if (calendar != null) {
        // Desactivar el selector de mes
        calendar.getMonthChooser().setEnabled(false);
        // Desactivar el selector de año
        calendar.getYearChooser().setEnabled(false);
        
        // Listener para permitir la selección de días
        calendar.getDayChooser().addPropertyChangeListener("day", evt -> {
            // Mantener la fecha actual al cambiar el día
            calendar.setDate(calendar.getDate());
        });
    }
}
    
        private void updateTextFields(Date fechaSeleccionada) {
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    if (fechaSeleccionada != null) {
        // Actualizar txtFechaAsignacion y txtFechaFinalizacion
        txtFechaAsignacion.setText(dateFormat.format(fechaSeleccionada));

        // Calcular y actualizar la fecha de finalización
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(fechaSeleccionada);
        calendar.add(Calendar.DAY_OF_YEAR, 7);
        txtFechaFinalizacion.setText(dateFormat.format(calendar.getTime()));
    }
}
        
        @Override
    public void addNotify() {
        super.addNotify();
        initCalendarios(); // Llama a initCalendarios para establecer las restricciones
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JCalendar CalendarioFechaAsignacion;
    public Vistas.elemetos.ButtonWI btnActualizar;
    public Vistas.elemetos.ButtonWI btnAgregar;
    public Vistas.elemetos.ButtonWI btnEliminar;
    public Vistas.elemetos.ButtonWI btnLimpiar;
    public javax.swing.JComboBox<String> cmbCita;
    public javax.swing.JComboBox<String> cmbEstado;
    public javax.swing.JComboBox<String> cmbServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tbAsignaciones;
    public javax.swing.JTextField txtCliente;
    public javax.swing.JTextArea txtDescripcion;
    public javax.swing.JTextField txtFechaAsignacion;
    public javax.swing.JTextField txtFechaFinalizacion;
    // End of variables declaration//GEN-END:variables
}
