/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

/**
 *
 * @author Jaimew
 */
import Controlador.ctrlClientes;
import Modelo.mdlClientes;
import Vistas.elementosTwo.TransparenteRoundedPanel;
import Vistas.elemetos.RoundedWhitePanel;
import java.text.ParseException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

public class frmClientes extends javax.swing.JFrame {

    /**
     * Creates new form frmClientes
     */
    public frmClientes() {
        initComponents();
        
         frmClientes vista = this;
        mdlClientes modelo = new mdlClientes();
        ctrlClientes controlador = new ctrlClientes(modelo, vista);

        vista.setVisible(true);
        setSize(1020, 720);
        setResizable(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transparenteRoundedPanel1 = new Vistas.elementosTwo.TransparenteRoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtduicliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtApellidoCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCorreoCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnAgregar = new Vistas.elemetos.Button();
        btnEliminar = new Vistas.elemetos.Button();
        btnActualizar = new Vistas.elemetos.Button();
        btnLimpiar = new Vistas.elemetos.Button();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        transparenteRoundedPanel1.setBackground(new java.awt.Color(0, 0, 0));
        transparenteRoundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Registra tus Clientes");
        transparenteRoundedPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel2.setText("Dui del cliente");
        transparenteRoundedPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 100, 20));
        transparenteRoundedPanel1.add(txtduicliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 140, -1));

        jLabel3.setText("Nombre ");
        transparenteRoundedPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));
        transparenteRoundedPanel1.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 140, -1));
        transparenteRoundedPanel1.add(txtApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 140, -1));

        jLabel4.setText("Apellido ");
        transparenteRoundedPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel5.setText("Buscar");
        transparenteRoundedPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 70, 20));
        transparenteRoundedPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 150, -1));

        jLabel6.setText("Correo Electronico ");
        transparenteRoundedPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 130, -1));
        transparenteRoundedPanel1.add(txtCorreoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 160, -1));

        jLabel7.setText("Telefono ");
        transparenteRoundedPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 90, -1));
        transparenteRoundedPanel1.add(txtTelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 170, -1));

        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbClientes);

        transparenteRoundedPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 880, 250));
        transparenteRoundedPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, 190, -1));

        jLabel8.setText("Contraseña ");
        transparenteRoundedPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 70, -1));

        btnAgregar.setText("Agregar");
        transparenteRoundedPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 150, 50));

        btnEliminar.setText("Eliminar");
        transparenteRoundedPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 150, 50));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        transparenteRoundedPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 150, 50));

        btnLimpiar.setText("Limpiar");
        transparenteRoundedPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 150, 50));

        add(transparenteRoundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public Vistas.elemetos.Button btnActualizar;
    public Vistas.elemetos.Button btnAgregar;
    public Vistas.elemetos.Button btnEliminar;
    public Vistas.elemetos.Button btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tbClientes;
    private Vistas.elementosTwo.TransparenteRoundedPanel transparenteRoundedPanel1;
    public javax.swing.JTextField txtApellidoCliente;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtContraseña;
    public javax.swing.JTextField txtCorreoCliente;
    public javax.swing.JTextField txtNombreCliente;
    public javax.swing.JTextField txtTelefonoCliente;
    public javax.swing.JTextField txtduicliente;
    // End of variables declaration//GEN-END:variables
}
