/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Controlador.ctrlCitas;
import Modelo.Clientes;
import Modelo.Empleados;
import Modelo.mdlCitas;
import Vistas.elementosTwo.TransparenteRoundedPanel;
import Vistas.elemetos.RoundedWhitePanel;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import java.awt.EventQueue;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;;

public class frmCitas extends TransparenteRoundedPanel {

    public frmCitas() {
        initComponents();
        
        frmCitas vista = this;
        mdlCitas modelito = new mdlCitas();
        Clientes Modelo = new Clientes();
        Empleados ModeloEm = new Empleados(); 
        citasCardsPanel cards = new citasCardsPanel(); // Inicializa el panel de tarjetas
        ctrlCitas contro = new ctrlCitas(modelito, vista, Modelo, ModeloEm,cards);
        vista.setVisible(true);

        // Formato para txtFecha (automáticamente añade guiones en formato yyyy-MM-dd)
        txtFecha.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE) {
                    e.consume(); // Sólo permite dígitos
                }

                String text = txtFecha.getText();
                if (text.length() == 4 || text.length() == 7) {
                    txtFecha.setText(text + "-");
                }
                if (text.length() >= 10) {
                    e.consume(); // Limita el tamaño a 10 caracteres (yyyy-MM-dd)
                }
            }
        });

        // Formato para txtHora (automáticamente añade dos puntos en formato HH:mm)
        txtHora.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE) {
                    e.consume(); // Sólo permite dígitos
                }

                String text = txtHora.getText();
                if (text.length() == 2) {
                    txtHora.setText(text + ":");
                }
                if (text.length() >= 5) {
                    e.consume(); // Limita el tamaño a 5 caracteres (HH:mm)
                }
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCitas = new javax.swing.JTable();
        calendar1 = new calendar.Calendar();
        btnActualizar = new javax.swing.JButton();
        btnAddCita = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        cmbCliente = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbEmpleado = new javax.swing.JComboBox<>();
        txtDEsc = new javax.swing.JTextField();
        citasCardsPanel1 = new Vistas.citasCardsPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Seleccionar cliente");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        jLabel7.setText("Selecciona la fecha de cita");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        jLabel2.setText("Selecionar Empleado");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));
        add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 120, -1));
        add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 130, -1));

        jLabel3.setText("Elije la hora de cita");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Agregar cita");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        tbCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbCitas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 670, 290));
        add(calendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 340, 310));

        btnActualizar.setText("Actualizar cita");
        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        btnAddCita.setText("Agregar Cita");
        add(btnAddCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        btnEliminar.setText("Eliminar cita");
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        cmbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 120, -1));

        jLabel6.setText("Descripccion de cita");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        cmbEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 130, -1));
        add(txtDEsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 170, -1));
        add(citasCardsPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnAddCita;
    public javax.swing.JButton btnEliminar;
    public calendar.Calendar calendar1;
    private Vistas.citasCardsPanel citasCardsPanel1;
    public javax.swing.JComboBox<String> cmbCliente;
    public javax.swing.JComboBox<String> cmbEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tbCitas;
    public javax.swing.JTextField txtDEsc;
    public javax.swing.JTextField txtFecha;
    public javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables
}
