/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Vistas.elementosTwo.TransparenteRoundedPanel;
import Vistas.elementosTwo.WhiteRoundedPanelF;
import Vistas.elemetos.RoundedWhitePanel;
import java.awt.Color;
/**
 *
 * @author pc
 */
public class frmInicio extends TransparenteRoundedPanel {

    /**
     * Creates new form frmInicio
     */
    public frmInicio() {
        setBackground(new Color(0, 0, 0, 0)); // Fondo transparente
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transparenteRoundedPanel1 = new Vistas.elementosTwo.TransparenteRoundedPanel();
        citasCardsPanel1 = new Vistas.citasCardsPanel();
        carrosCardsPanel1 = new Vistas.carrosCardsPanel();

        setBackground(new java.awt.Color(0, 0, 0));

        transparenteRoundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        transparenteRoundedPanel1.add(citasCardsPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 980, -1));
        transparenteRoundedPanel1.add(carrosCardsPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 950, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transparenteRoundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transparenteRoundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vistas.carrosCardsPanel carrosCardsPanel1;
    private Vistas.citasCardsPanel citasCardsPanel1;
    private Vistas.elementosTwo.TransparenteRoundedPanel transparenteRoundedPanel1;
    // End of variables declaration//GEN-END:variables
}
