/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Vistas.elementosTwo.TransparenteRoundedPanel;
import Vistas.elemetos.RoundedWhitePanel;
import java.awt.Color;
/**
 *
 * @author pc
 */
public class frmInicio extends TransparenteRoundedPanel {

    /**
     * Creates new form frmInicio
     */
    public frmInicio() {
        setBackground(new Color(0, 0, 0, 0)); // Fondo transparente
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transparenteRoundedPanel1 = new Vistas.elementosTwo.TransparenteRoundedPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Inicio :)");

        javax.swing.GroupLayout transparenteRoundedPanel1Layout = new javax.swing.GroupLayout(transparenteRoundedPanel1);
        transparenteRoundedPanel1.setLayout(transparenteRoundedPanel1Layout);
        transparenteRoundedPanel1Layout.setHorizontalGroup(
            transparenteRoundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparenteRoundedPanel1Layout.createSequentialGroup()
                .addGap(466, 466, 466)
                .addComponent(jLabel1)
                .addContainerGap(498, Short.MAX_VALUE))
        );
        transparenteRoundedPanel1Layout.setVerticalGroup(
            transparenteRoundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparenteRoundedPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(608, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transparenteRoundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transparenteRoundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private Vistas.elementosTwo.TransparenteRoundedPanel transparenteRoundedPanel1;
    // End of variables declaration//GEN-END:variables
}
