/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Controlador.ctrlInventario;
import Modelo.ProductosRepuestos;
import Modelo.mdlInventario;
import Modelo.Proveedores;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;

/**
 *
 * @author Kevin
 */
public class frmInventario extends javax.swing.JPanel {

    /**
     * Creates new form frmInventario
     */
    public frmInventario() {
        initComponents();
        frmInventario vista = this;
        mdlInventario modelo = new mdlInventario();
        ProductosRepuestos mProductosRepuestos = new ProductosRepuestos();
        Proveedores mProveedor = new Proveedores();
        ctrlInventario controlador = new ctrlInventario(modelo, vista, mProductosRepuestos, mProveedor);
        
        vista.setVisible(true);
        
        
        
        calendar2.addCalendarSelectedListener((MouseEvent evt, calendar.model.ModelDate date) -> {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            txtFechaInventario.setText(dateFormat.format(date.toDate())); // Actualiza txtFecha con la fecha seleccionada
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbProdcutosRepuestos = new javax.swing.JComboBox<>();
        cmbProveedores = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        calendar2 = new calendar.Calendar();
        txtFechaInventario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInventario = new javax.swing.JTable();
        btnGuardarInventario = new Vistas.elemetos.ButtonWI();
        btnActualizarInventario = new Vistas.elemetos.ButtonWI();
        btnBorrarInventario = new Vistas.elemetos.ButtonWI();
        btnLimpiarInventario = new Vistas.elemetos.ButtonWI();
        btnBuscarInventario = new Vistas.elemetos.ButtonWI();
        txtBuscarInventario = new Vistas.elementosTwo.MyTextField();
        btnProductosRepuestos = new Vistas.elemetos.ButtonWI();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbProdcutosRepuestos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbProdcutosRepuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 271, 32));

        cmbProveedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 271, 32));
        add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 271, 32));

        calendar2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                calendar2PropertyChange(evt);
            }
        });
        add(calendar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 90, 390, 340));

        txtFechaInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaInventarioActionPerformed(evt);
            }
        });
        add(txtFechaInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 271, 32));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Producto o Repuesto");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Proveedor:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cantidad:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ultima fecha de suministro:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbInventario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 62, 938, 200));

        btnGuardarInventario.setText("Guardar");
        btnGuardarInventario.setSuffixIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/icguardaraloadriel.png"))); // NOI18N
        jPanel1.add(btnGuardarInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 15, 150, -1));

        btnActualizarInventario.setText("Editar");
        btnActualizarInventario.setSuffixIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/iceditaralokevon.png"))); // NOI18N
        jPanel1.add(btnActualizarInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 15, 150, -1));

        btnBorrarInventario.setText("Eliminar");
        btnBorrarInventario.setSuffixIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/icborraralojosue.png"))); // NOI18N
        jPanel1.add(btnBorrarInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 15, 150, -1));

        btnLimpiarInventario.setText("Limpiar");
        btnLimpiarInventario.setSuffixIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/iclimpiaralojaime.png"))); // NOI18N
        jPanel1.add(btnLimpiarInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 15, 150, -1));

        btnBuscarInventario.setText("Buscar");
        jPanel1.add(btnBuscarInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 15, 80, -1));

        txtBuscarInventario.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/iconbuscar2.png"))); // NOI18N
        jPanel1.add(txtBuscarInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 20, 234, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 980, -1));

        btnProductosRepuestos.setText("Crear Producto o Repuesto");
        btnProductosRepuestos.setSuffixIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/icguardaraloadriel.png"))); // NOI18N
        add(btnProductosRepuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 210, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void calendar2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_calendar2PropertyChange
          if ("calendar".equals(evt.getPropertyName())) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            // Actualizar el campo de texto de la fecha
            txtFechaInventario.setText(dateFormat.format(calendar2.getSelectedDate()));
        }
    }//GEN-LAST:event_calendar2PropertyChange

    private void txtFechaInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaInventarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public Vistas.elemetos.ButtonWI btnActualizarInventario;
    public Vistas.elemetos.ButtonWI btnBorrarInventario;
    public Vistas.elemetos.ButtonWI btnBuscarInventario;
    public Vistas.elemetos.ButtonWI btnGuardarInventario;
    public Vistas.elemetos.ButtonWI btnLimpiarInventario;
    public Vistas.elemetos.ButtonWI btnProductosRepuestos;
    public calendar.Calendar calendar2;
    public javax.swing.JComboBox<String> cmbProdcutosRepuestos;
    public javax.swing.JComboBox<String> cmbProveedores;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tbInventario;
    public Vistas.elementosTwo.MyTextField txtBuscarInventario;
    public javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtFechaInventario;
    // End of variables declaration//GEN-END:variables
}
