/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Controlador.ctrlEmpleados;
import Modelo.Usuarios;
import Modelo.mdlEmpleados;
import Vistas.elementosTwo.TransparenteRoundedPanel;
import Vistas.elemetos.RoundedWhitePanel;


public class frmUsuarios extends TransparenteRoundedPanel{

    public frmUsuarios() {
        initComponents();
        
        mdlEmpleados modelo = new mdlEmpleados();
        frmUsuarios vista = this;
        Usuarios mUsuarios = new Usuarios();
        ctrlEmpleados controlador = new ctrlEmpleados(modelo, vista, mUsuarios);
        
        vista.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtdui = new javax.swing.JFormattedTextField();
        cmbCorreoEmpleado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnActualizar = new Vistas.elemetos.ButtonA();
        btnGuardar = new Vistas.elemetos.ButtonA();
        btnEliminar = new Vistas.elemetos.ButtonA();
        jScrollPane1 = new javax.swing.JScrollPane();
        dtgempleado = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JFormattedTextField();
        txtapellido = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnLimpiar = new Vistas.elemetos.ButtonA();
        btnSubirImagen = new javax.swing.JButton();
        btnNewUser = new javax.swing.JButton();
        pnlImagen = new javax.swing.JPanel();
        txtImagenUrl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFecha = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Empleados");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 170, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel3.setText("Apellidos");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel7.setText("Dui:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 220, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel10.setText("Correo del Empleado");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 110, 20));

        txtdui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtduiActionPerformed(evt);
            }
        });
        add(txtdui, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 220, 30));

        cmbCorreoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbCorreoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 220, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel9.setText("Telefono");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.setToolTipText("");
        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, 120, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("");
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 120, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("");
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 120, -1));

        dtgempleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dtgempleado);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 830, 220));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 30, 30));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 30, 10));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel11.setText("Nombres");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
        add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 220, 30));
        add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 220, 30));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 500, -1, -1));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 666, 60, 30));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("");
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 120, -1));

        btnSubirImagen.setText("Subir Imagen");
        add(btnSubirImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, -1, 30));

        btnNewUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/mas.png"))); // NOI18N
        add(btnNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 30, 30));

        pnlImagen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtImagenUrl.setMinimumSize(new java.awt.Dimension(50, 50));
        pnlImagen.add(txtImagenUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 110));

        add(pnlImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 160, 110));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel5.setText("FechaNacimiento");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, -1, -1));
        add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtduiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtduiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtduiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public Vistas.elemetos.ButtonA btnActualizar;
    public Vistas.elemetos.ButtonA btnEliminar;
    public Vistas.elemetos.ButtonA btnGuardar;
    public Vistas.elemetos.ButtonA btnLimpiar;
    public javax.swing.JButton btnNewUser;
    public javax.swing.JButton btnSubirImagen;
    public javax.swing.JComboBox<String> cmbCorreoEmpleado;
    public javax.swing.JTable dtgempleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlImagen;
    public com.toedter.calendar.JDateChooser txtFecha;
    public javax.swing.JLabel txtImagenUrl;
    public javax.swing.JTextField txtTelefono;
    public javax.swing.JFormattedTextField txtapellido;
    public javax.swing.JFormattedTextField txtdui;
    public javax.swing.JFormattedTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
